
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kumar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        loginPanel = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usernameValue = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordValue = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        orlabel = new javax.swing.JLabel();
        customerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");

        loginPanel.setBackground(new java.awt.Color(34, 49, 63));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.setToolTipText("");
        loginPanel.setLayout(null);

        welcome.setFont(new java.awt.Font("Harlow Solid Italic", 1, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome Back!");
        loginPanel.add(welcome);
        welcome.setBounds(67, 55, 364, 61);

        username.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        loginPanel.add(username);
        username.setBounds(147, 159, 90, 24);

        usernameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameValueActionPerformed(evt);
            }
        });
        loginPanel.add(usernameValue);
        usernameValue.setBounds(147, 193, 197, 32);

        password.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        loginPanel.add(password);
        password.setBounds(147, 270, 110, 24);

        passwordValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordValueActionPerformed(evt);
            }
        });
        loginPanel.add(passwordValue);
        passwordValue.setBounds(147, 304, 197, 32);

        loginButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(147, 384, 75, 40);

        clearButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        loginPanel.add(clearButton);
        clearButton.setBounds(275, 384, 69, 40);

        orlabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        orlabel.setForeground(new java.awt.Color(255, 255, 255));
        orlabel.setText("Or");
        loginPanel.add(orlabel);
        orlabel.setBounds(232, 456, 40, 33);

        customerButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        customerButton.setText("Continue as Customer");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        loginPanel.add(customerButton);
        customerButton.setBounds(147, 507, 197, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Login.png"))); // NOI18N
        loginPanel.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        Customer customerWindow= new Customer(); 
        customerWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_customerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String user = usernameValue.getText();
        String password = passwordValue.getText();
        if(user.equals("") & password.equals("")){
            JOptionPane.showMessageDialog(loginPanel,"Please enter Username/Password.");
        }else if(user.equals("admin")& password.equals("admin")){
            BikeInfo staff= new BikeInfo();
            staff.setVisible(true);
            dispose();
            usernameValue.setText(null);
            passwordValue.setText(null);
        }else{
            JOptionPane.showMessageDialog(loginPanel,"Invalid Username/Password. Try Again.");
        } 

        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordValueActionPerformed

    private void usernameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameValueActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
       usernameValue.setText(null);
       passwordValue.setText(null);
        
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel orlabel;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordValue;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameValue;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
